name: Sync Spec

on:
  repository_dispatch:
    types: [spec_updated]

jobs:
  fetch-and-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Spoke Code
        uses: actions/checkout@v4

      - name: Fetch Latest Spec from Hub
        run: |
          FILE_NAME="${{ github.event.client_payload.file_name }}"
          
          # 2. Inject the FILE_NAME variable into the API URL and output path
          curl -H "Authorization: Bearer ${{ secrets.CROSS_REPO_PAT }}" \
              -H "Accept: application/vnd.github.v3.raw" \
              -L https://api.github.com/repos/techoabhishek/cicd-hub-repo/contents/specs/$FILE_NAME \
              -o ./$FILE_NAME
              
      - name: Verify Download
        run: |
          echo "Downloaded Spec:"
          cat ./${{ github.event.client_payload.file_name }}